language: java

services:
  - mysql -u root -p root

addons:
  apt:
    sources:
      - purge mysql-client-core-5.6
      - autoclean
      - autoremove
      - mysql-5.7-trusty
    packages:
      - mysql-client-core-5.5
      - mysql-server

dist: trusty

sudo: required

before_script:
  - mysql -e 'create database csuser_db;'