language: java

services:
  - mysql

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS csuser_db;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS csuser_db;'
  - mysql -u root --root-character-set=utf8
  - mysql -e 'CREATE SCHEMA csuser_db;'