language: java

services:
  - mysql

before_install:
- sudo mysql -e "CREATE USER 'csuser'@'localhost' IDENTIFIED BY 'csuser'; GRANT ALL PRIVILEGES ON * . * TO 'csuser'@'localhost'; FLUSH PRIVILEGES;"
- sudo mysql_upgrade
- sudo service mysql restart

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS csuser_db;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS csuser_db;'
  - echo "USE mysql; CREATE USER 'csuser'@'localhost' IDENTIFIED BY 'csuser'; GRANT ALL PRIVILEGES ON * . * TO 'csuser'@'localhost'; FLUSH PRIVILEGES;
  - mysql -e 'CREATE SCHEMA csuser_db;'

after_failure:
    - cat "$TCI_D_MYSQL_ROOT/mysql.err"