language: java

services:
  - mysql -u root -p root

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

before_script:
  - mysql -e 'create database csuser_db;'